# Generated by Django 4.0.5 on 2022-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=25)),
                ('customerPhone', models.CharField(max_length=10)),
                ('customerAddress', models.TextField(max_length=100)),
                ('customerEmail', models.EmailField(max_length=50)),
                ('customerPasw', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
